### ISSUE TITLE
can't search for `txtPsw`

### ISSUE THREAD

**Issue by luzlab** [tomsoftware/EOS-Formats#1]
I was looking for the default administrator and logdbadmin password for an EOS and realized it's probably stored in this repo. I tried searching for the default value of `txtPsw`, but github couldn't find it.

![screen shot 2017-07-31 at 5 04 13 pm](https://user-images.githubusercontent.com/9924835/28803549-4c761728-7612-11e7-9eea-38d8ff0b3678.png)

**Comment by tomsoftware** [comment]
Have a look in the [/Demo/Form1.Designer.cs](https://github.com/tomsoftware/EOS-Formats/blob/master/Demo/Form1.Designer.cs) file for more information about this.
