### ISSUE TITLE
.sli Integration with PySLM

### ISSUE THREAD

**Issue by drlukeparry** [tomsoftware/EOS-Formats#3]
Hi Tom,

In the future, am looking into integrate the .sl reader with the [PySLM](https://github.com/drlukeparry/pyslm) project as a reader/writer translator, which can be used for creating build files. 

I am still unsure about the legal requirements (in relation to it being opensource), but I intend atleast to make a simple python equivalent based on your work. 

If there is anything you can offer that may assist, I would be grateful.

Many Thanks,
Luke

**Comment by tomsoftware** [comment]
it's MIT Licence so you can do what you want without any warranty..i. f you want you can add me to your "credits" but even this is not required
